route:
  receiver: 'Mail Alert'
  # group_by: [ alertname ]
  repeat_interval: 30s
  group_wait: 15s
  group_interval: 15s

receivers:
  - name: 'Mail Alert'
    email_configs:
      - smarthost: 'smtp.gmail.com:587'
        auth_username: 'devgainsrequets@gmail.com'
        auth_password: "irky dxwv bcij xbrj"
        from: 'devgainsrequets@gmail.com'
        to: 'ahmad.harkous@epita.fr'
        headers:
          subject: 'Prometheus Mail Alerts'