receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4321
      http:
        endpoint: 0.0.0.0:4319
    

exporters:
  # Export traces to Tempo
  otlp/tempo:
    endpoint: "http://tempo:4317"
    tls:
      insecure: true
  # Export logs directly to Loki
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tls:
      insecure: true


service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/tempo]
    logs:
      receivers: [otlp]
      exporters: [loki]
