groups:
- name: Example
  rules:
    - alert: InstanceDown
      expr: up == 0
      for: 15s
      labels:
        severity: critical
      annotations:
        summary: "Instance [{{ $labels.instance }}] down"
        description: "[{{ $labels.instance }}] of job {{ $labels.job }} has been down for more than 15 seconds."

#- name: NodeMemUsgae
 # rules:
 #   - alert: HostMemoryIsUnderutilized
  #    expr: ({__name__="node_memory_MemAvailable_bytes", instance="node-exporter:9200", job="node"} > 80)
   #   for: 15s
   #   labels:
   #     severity: critical
   #   annotations:
   #     summary: Host Memory is underutilized (instance {{ $labels.instance }})
    #    description: "Node memory is < 20% for 1 week. Consider reducing memory space. (instance {{ $labels.instance }})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


#- name : NodeCpuUsage
 # rules:
  #  - alert: HostCpuIsUnderutilized
   #   expr: ({__name__="node_cpu_seconds_total", instance="node-exporter:9200", job="node"} > 80)
    #  for: 15s
     # labels:
      #  severity: critical
      #annotations:
      #  summary: Host CPU is underutilized (instance {{ $labels.instance }})
      #  description: "Node CPU is < 20% for 1 week. Consider reducing CPU space. (instance {{ $labels.instance }})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

#- name: NodeDiskUsage
 # rules:
  #  - alert: HostDiskIsUnderutilized
   #   expr: ({__name__="node_filesystem_avail_bytes", instance="node-exporter:9200", job="node"} > 80)
    #  for: 15s
     # labels:
      #  severity: critical
      #annotations:
       # summary: Host Disk is underutilized (instance {{ $labels.instance }})
        #description: "Node Disk is < 20% for 1 week. Consider reducing Disk space. (instance {{ $labels.instance }})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

#fast api rules on mnist-api:7000

- name: FastApiRequestDuration
  rules:
    - alert: FastApiRequestDurationHigh
      expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job="mnist_api_node", le="+Inf"}[5m])) by (job, le)) > 0.5
      for: 15s
      labels:
        severity: warning
      annotations:
        summary: FastAPI request duration high (instance {{ $labels.instance }})
        description: "FastAPI request duration is > 0.5s for 5 minutes. (instance {{ $labels.instance }})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

- name: FastApiRequestError
  rules:
    - alert: FastApiRequestErrorHigh
      expr: sum(rate(http_request_duration_seconds_count{job="mnist_api_node", status="500"}[5m])) by (job) > 0.5
      for: 15s
      labels:
        severity: warning
      annotations:
        summary: FastAPI request error high (instance {{ $labels.instance }})
        description: "FastAPI request error is > 0.5 for 5 minutes. (instance {{ $labels.instance }})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


#- name: HTTP_Status_Failure
 # rules:
 #   - alert: BlackboxProbeHttpFailure
 #     expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
 #     for: 0m
 #     labels:
  #      severity: critical
 #     annotations:
  ##      summary: Blackbox probe HTTP failure (instance {{ $labels.instance }})
  #      description: "HTTP status code is not 200-399\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

#- name: SSL_Expiry
  #rules:
  #  - alert: BlackboxSslCertificateWillExpireSoon
  #    expr: 0 <= round((last_over_time(probe_ssl_earliest_cert_expiry[10m]) - time()) / 86400, 0.1) < 60
   #   for: 0m
   #   labels:
   #     severity: warning
     # annotations:
      #  summary: Blackbox SSL certificate will expire soon (instance {{ $labels.instance }})
       # description: "SSL certificate expires in less than 200 days\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
